name: 'Deploy AWS Lambda'

on:
  push:
    branches:
     - main
    pull_request: 

jobs:
  deploy:
    name: Deploy AWS Lambda Function
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v2

    # Install the node dependencies
    - name: Install Dependencies
      run: yarn  

    # build phase
    - name: Build
      run: yarn build  

    # move node_modules to dist directory
    - name: Move node_modules to dist
      run: mv node_modules dist/node_modules  

    # Zip the contents to be deployed
    - name: Zip
      run: (cd dist && zip -qq -r ../function.zip ./)  

    # Deploy to AWS
    - name: Deploy to AWS
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        aws_region: us-east-1
        function_name: tf_function
        zip_file: function.zip
        memory_size: 128
        timeout: 10
