name: 'Deploy AWS Lambda'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the node dependencies
    - name: Install Dependencies
      run: yarn  

    # build phase
    - name: Build
      run: yarn build  

    # move node_modules to dist directory
    - name: Move node_modules to dist
      run: mv node_modules dist/node_modules  

    - name: Zip the contents to be deployed
      run: (cd dist && zip -r ../function.zip .)  

    # Deploy to AWS
    - name: Deploy to AWS
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: tf_function
        zip_file: function.zip
